### ISSUE TITLE
Absolutely anywhere but here

### ISSUE THREAD

**Issue by drew0036** [drew0036/saas-website#1]
@muxlowc Hello again! Thank you so much for all your help!

I'm having this weird issue where if I use absolute and relative in multiple locations, my second use of absolute gets pulled away to the first instance. 

![Screen Shot 2020-04-17 at 10 13 47 PM](https://user-images.githubusercontent.com/55107709/79625750-1d006a80-80f9-11ea-8bcd-f0c347252ddf.png)

See photo for example. My form info for gathering emails for the newsletter is up on top of my banner call to action. It there a specific way I can link the appropriate code together. 

Thank you!

**Comment by muxlowc** [comment]
@drew0036 Did you fix this? it looks good on my end!

**Comment by drew0036** [comment]
Not quite, I removed the second image to put in a background colour. It looks good enough.
