### ISSUE TITLE
Table Images Misbehaving

### ISSUE THREAD

**Issue by drew0036** [drew0036/saas-website#2]
![Screen Shot 2020-04-19 at 12 04 35 AM](https://user-images.githubusercontent.com/55107709/79679183-966b8c00-81d1-11ea-8a22-ec976b1fdeda.png)

Hello @muxlowc!

I'm having trouble getting the images in my table to sit in a row. Any suggestions, I have not seen anyone put imgs in a table yet so I don't even know if this is doable? 

Also does this count as my progress check-in?

Thank you!

**Comment by muxlowc** [comment]
@drew0036  so your `<tr>` were kind of sitting outside - they either need to be inside of a tbody, or thead.. also, you need to have your img-flex class on the image, not the tr

```
<tbody>
        <tr>
          <td><img class="img-flex" src="images/product-1.png" alt=""></td>
          <td><img class="img-flex" src="images/product-2.png" alt=""></td>
          <td><img class="img-flex" src="images/product-3.png" alt=""></td>
        </tr>
        <tr>
```

That should work!

**Comment by muxlowc** [comment]
and yep , i just marked off your check-in  mark!

**Comment by drew0036** [comment]
Thank you! 😄
