### ISSUE TITLE
Please translate?

### ISSUE THREAD

**Issue by drew0036** [drew0036/saas-website#3]
![Screen Shot 2020-04-20 at 8 27 34 PM](https://user-images.githubusercontent.com/55107709/79812015-98565c00-8345-11ea-97c8-76ddb840a83c.png)

Hello @muxlowc! I'm not sure why Marbot is mad at me for this. I can't see how they're all connected, can you please translate? Thank you!

**Comment by muxlowc** [comment]
@drew0036 

So I think what its saying is that every part of your code should be inside of a role="" .. The easiest way to do this is to have:

```
<header></header>
<main>
  <section></section>
  <section></section>
  <section></section>
</main>
<footer></footer>
```
You seem to have a section or two that are floating outside of your `<main>` meaning, they are not including in any landmarks (ie roles). So you might just need to switch a few tags around!

**Comment by drew0036** [comment]
OOOOOOOOHHHHHHHhhhhhh....... that makes a lot of sense. Thank you! <3
