### ISSUE TITLE
Skiplinks Missing? Maybe?

### ISSUE THREAD

**Issue by drew0036** [drew0036/saas-website#4]
![Screen Shot 2020-04-20 at 10 34 05 PM](https://user-images.githubusercontent.com/55107709/79818985-0fe0b700-8357-11ea-86d7-a1e6ac8a25e0.png)

Hey @muxlowc! 

I have skip links to the nav and main on each page. I'm not sure why it says I don't on some pages but not the homepage. Or do I have to put a skip link on every single section? And if so would that be something like:   < section id="unique-id" tabindex="0" >  because there isn't a role for it?

Thank you!

**Comment by drew0036** [comment]
Ok been working on it. Does it have to do with something else?

**Comment by muxlowc** [comment]
@drew0036 

I dont think it's talking about your nav for this issue - I think it wants you to have at least one link on each page that isnt part of the nav (ie. a read more link), and then on top of that, it needs to have a focus state, and yes maybe add a tabindex to the links as well

**Comment by drew0036** [comment]
It worked! Thank you!

**Comment by drew0036** [comment]
It worked! Thank you!
